name: Build on Tag

on:
 watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper
    
    - name: text
      run: |
          git clone --recursive https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git -b olive-q-oss  --depth 1
          cd Xiaomi_Kernel_OpenSource
    
    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: text
      with:
        arch: arm64
        compiler: gcc/10
        defconfig: olive-perf_defconfig
        image: Image.gz-dtb

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
